
const MODULE_PREFIX = "HOME_DASHBOARD_MODULE"
const SAGA_PREFIX = MODULE_PREFIX + "__SAGA__"
const REDUCER_PREFIX = MODULE_PREFIX + "__REDUCER__"

export const SAGA_ACTION_TYPES = {
    FETCH_ARTICLES: `${SAGA_PREFIX}_FETCH_ARTICLES`,
}

export const REDUCER_ACTION_TYPES = {
    SET_PROCESSING: `${REDUCER_PREFIX}_TRANSACTION_PROCESSING`,
    FETCH_ARTICLES_COMPLETED: `${REDUCER_PREFIX}_FETCH_ARTICLES_COMPLETED`
}